#!/bin/bash

# running everything we need for development
mongod &
supervisor -w . server.js &
./node_modules/stylus/bin/stylus public/css/app.styl -w &
./node_modules/browserify/bin/cmd.js public/js/controllers.js public/js/calc.js public/js/calcExtra.js -o public/js/bundle.js -w &
